import React, { useState } from 'react';

const popularGreekWords = [
  { word: 'και', translation: 'and', transliteration: 'kai' },
  { word: 'είμαι', translation: 'am', transliteration: 'eimai' },
  { word: 'έχω', translation: 'have', transliteration: 'echo' },
  { word: 'αυτός', translation: 'he', transliteration: 'aftos' },
  { word: 'αυτή', translation: 'she', transliteration: 'afti' },
  { word: 'είναι', translation: 'is', transliteration: 'einai' },
  { word: 'όχι', translation: 'no', transliteration: 'ochi' },
  { word: 'ναι', translation: 'yes', transliteration: 'nai' },
  { word: 'εδώ', translation: 'here', transliteration: 'edo' },
  { word: 'εκεί', translation: 'there', transliteration: 'eki' },
  { word: 'πολύ', translation: 'much', transliteration: 'poly' },
  { word: 'λίγο', translation: 'little', transliteration: 'ligo' },
  { word: 'μεγάλο', translation: 'big', transliteration: 'megalo' },
  { word: 'μικρό', translation: 'small', transliteration: 'mikro' },
  { word: 'καλό', translation: 'good', transliteration: 'kalo' },
  { word: 'κακό', translation: 'bad', transliteration: 'kako' },
  { word: 'παιδί', translation: 'child', transliteration: 'paidi' },
  { word: 'άνθρωπος', translation: 'man', transliteration: 'anthropos' },
  { word: 'γυναίκα', translation: 'woman', transliteration: 'gynaika' },
  { word: 'σπίτι', translation: 'house', transliteration: 'spiti' },
  { word: 'δρόμος', translation: 'street', transliteration: 'dromos' },
  { word: 'αυτοκίνητο', translation: 'car', transliteration: 'aftokinito' },
  { word: 'ποδήλατο', translation: 'bicycle', transliteration: 'podilato' },
  { word: 'πλοίο', translation: 'ship', transliteration: 'ploio' },
  { word: 'αεροπλάνο', translation: 'airplane', transliteration: 'aeroplano' },
  { word: 'τρένο', translation: 'train', transliteration: 'treno' },
  { word: 'λεωφορείο', translation: 'bus', transliteration: 'leoforio' },
  { word: 'ταξί', translation: 'taxi', transliteration: 'taksi' },
  { word: 'ποδήλατο', translation: 'bicycle', transliteration: 'podilato' },
  { word: 'αθλητισμός', translation: 'sports', transliteration: 'athlitismos' },
  { word: 'ποδόσφαιρο', translation: 'soccer', transliteration: 'podosfairo' },
  { word: 'μπάσκετ', translation: 'basketball', transliteration: 'mpasket' },
  { word: 'βόλεϊ', translation: 'volleyball', transliteration: 'bolei' },
  { word: 'τένις', translation: 'tennis', transliteration: 'tenis' },
  { word: 'γκολφ', translation: 'golf', transliteration: 'golf' },
  { word: 'ποδηλασία', translation: 'cycling', transliteration: 'podilasia' },
  { word: 'κωπηλασία', translation: 'rowing', transliteration: 'kopilasia' },
  { word: 'ιππασία', translation: 'horse riding', transliteration: 'ippasia' },
  { word: 'παιχνίδι', translation: 'game', transliteration: 'paichnidi' },
  { word: 'βιβλίο', translation: 'book', transliteration: 'vivlio' },
  { word: 'εφημερίδα', translation: 'newspaper', transliteration: 'efimerida' },
  { word: 'τηλεόραση', translation: 'television', transliteration: 'tileorasi' },
  { word: 'ραδιόφωνο', translation: 'radio', transliteration: 'radiofono' },
  { word: 'κινηματογράφος', translation: 'cinema', transliteration: 'kinimatografos' },
  { word: 'θεάτρο', translation: 'theater', transliteration: 'theatro' },
  { word: 'μουσική', translation: 'music', transliteration: 'mousiki' },
  { word: 'χορός', translation: 'dance', transliteration: 'choros' },
  { word: 'ζωγραφική', translation: 'painting', transliteration: 'zografiki' },
  { word: 'γλυπτική', translation: 'sculpture', transliteration: 'glyptiki' },
  { word: 'αρχιτεκτονική', translation: 'architecture', transliteration: 'architektoniki' },
  { word: 'φωτογραφία', translation: 'photography', transliteration: 'fotografia' },
  { word: 'βίντεο', translation: 'video', transliteration: 'bideo' },
  { word: 'ηλεκτρονικός', translation: 'electronic', transliteration: 'ilektronikos' },
  { word: 'υπολογιστής', translation: 'computer', transliteration: 'ypologistis' },
  { word: 'διαδίκτυο', translation: 'internet', transliteration: 'diadiktyo' },
  { word: 'τηλέφωνο', translation: 'telephone', transliteration: 'tilefono' },
  { word: 'fax', translation: 'fax', transliteration: 'fax' },
  { word: 'τηλεγράφημα', translation: 'telegram', transliteration: 'tilegrafima' },
  { word: 'επιστολή', translation: 'letter', transliteration: 'epistoli' },
  { word: 'κάρτα', translation: 'card', transliteration: 'karta' },
  { word: 'χαρτογράφος', translation: 'map', transliteration: 'chartografos' },
  { word: 'οδηγός', translation: 'guide', transliteration: 'odigos' },
  { word: 'λεξικό', translation: 'dictionary', transliteration: 'lexiko' },
  { word: 'εγκυκλοπαίδεια', translation: 'encyclopedia', transliteration: 'egkyklopaideia' },
  { word: 'βιβλιοθήκη', translation: 'library', transliteration: 'vivliothiki' },
  { word: 'αρχείο', translation: 'archive', transliteration: 'arxeio' },
  { word: 'μουσείο', translation: 'museum', transliteration: 'mouseio' },
  { word: 'πάρκο', translation: 'park', transliteration: 'parko' },
  { word: 'κήπος', translation: 'garden', transliteration: 'kipos' },
  { word: 'δάσος', translation: 'forest', transliteration: 'dasos' },
  { word: 'βουνό', translation: 'mountain', transliteration: 'vouno' },
  { word: 'ποταμός', translation: 'river', transliteration: 'potamos' },
  { word: 'λίμνη', translation: 'lake', transliteration: 'limni' },
  { word: 'θάλασσα', translation: 'sea', transliteration: 'thalassa' },
  { word: 'αεροδρόμιο', translation: 'airport', transliteration: 'aerodromio' },
  { word: 'λιμάνι', translation: 'port', transliteration: 'limani' },
  { word: 'στάση', translation: 'station', transliteration: 'stasi' },
  { word: 'σιδηροδρομικός', translation: 'railway', transliteration: 'siderodromikos' },
  { word: 'λεωφορείο', translation: 'bus', transliteration: 'leoforio' },
  { word: 'ταξί', translation: 'taxi', transliteration: 'taksi' },
  { word: 'ποδήλατο', translation: 'bicycle', transliteration: 'podilato' },
  { word: 'αθλητισμός', translation: 'sports', transliteration: 'athlitismos' },
  { word: 'ποδόσφαιρο', translation: 'soccer', transliteration: 'podosfairo' },
  { word: 'μπάσκετ', translation: 'basketball', transliteration: 'mpasket' },
  { word: 'βόλεϊ', translation: 'volleyball', transliteration: 'bolei' },
  { word: 'τένις', translation: 'tennis', transliteration: 'tenis' },
  { word: 'γκολφ', translation: 'golf', transliteration: 'golf' },
  { word: 'ποδηλασία', translation: 'cycling', transliteration: 'podilasia' },
  { word: 'κωπηλασία', translation: 'rowing', transliteration: 'kopilasia' },
  { word: 'ιππασία', translation: 'horse riding', transliteration: 'ippasia' },
  { word: 'παιχνίδι', translation: 'game', transliteration: 'paichnidi' },
  { word: 'βιβλίο', translation: 'book', transliteration: 'vivlio' },
  { word: 'εφημερίδα', translation: 'newspaper', transliteration: 'efimerida' },
  { word: 'τηλεόραση', translation: 'television', transliteration: 'tileorasi' },
  { word: 'ραδιόφωνο', translation: 'radio', transliteration: 'radiofono' },
  { word: 'κινηματογράφος', translation: 'cinema', transliteration: 'kinimatografos' },
  { word: 'θεάτρο', translation: 'theater', transliteration: 'theatro' },
  { word: 'μουσική', translation: 'music', transliteration: 'mousiki' },
  { word: 'χορός', translation: 'dance', transliteration: 'choros' },
  { word: 'ζωγραφική', translation: 'painting', transliteration: 'zografiki' },
  { word: 'γλυπτική', translation: 'sculpture', transliteration: 'glyptiki' },
  { word: 'αρχιτεκτονική', translation: 'architecture', transliteration: 'architektoniki' },
  { word: 'φωτογραφία', translation: 'photography', transliteration: 'fotografia' },
  { word: 'βίντεο', translation: 'video', transliteration: 'bideo' },
  { word: 'ηλεκτρονικός', translation: 'electronic', transliteration: 'ilektronikos' },
  { word: 'υπολογιστής', translation: 'computer', transliteration: 'ypologistis' },
  { word: 'διαδίκτυο', translation: 'internet', transliteration: 'diadiktyo' },
  { word: 'τηλέφωνο', translation: 'telephone', transliteration: 'tilefono' },
  { word: 'fax', translation: 'fax', transliteration: 'fax' },
  { word: 'τηλεγράφημα', translation: 'telegram', transliteration: 'tilegrafima' },
  { word: 'επιστολή', translation: 'letter', transliteration: 'epistoli' },
  { word: 'κάρτα', translation: 'card', transliteration: 'karta' },
  { word: 'χαρτογράφος', translation: 'map', transliteration: 'chartografos' },
  { word: 'οδηγός', translation: 'guide', transliteration: 'odigos' },
  { word: 'λεξικό', translation: 'dictionary', transliteration: 'lexiko' },
  { word: 'εγκυκλοπαίδεια', translation: 'encyclopedia', transliteration: 'egkyklopaideia' },
  { word: 'βιβλιοθήκη', translation: 'library', transliteration: 'vivliothiki' },
  { word: 'αρχείο', translation: 'archive', transliteration: 'arxeio' },
  { word: 'μουσείο', translation: 'museum', transliteration: 'mouseio' },
  { word: 'πάρκο', translation: 'park', transliteration: 'parko' },
  { word: 'κήπος', translation: 'garden', transliteration: 'kipos' },
  { word: 'δάσος', translation: 'forest', transliteration: 'dasos' },
  { word: 'βουνό', translation: 'mountain', transliteration: 'vouno' },
  { word: 'ποταμός', translation: 'river', transliteration: 'potamos' },
  { word: 'λίμνη', translation: 'lake', transliteration: 'limni' },
  { word: 'θάλασσα', translation: 'sea', transliteration: 'thalassa' },
  { word: 'αεροδρόμιο', translation: 'airport', transliteration: 'aerodromio' },
  { word: 'λιμάνι', translation: 'port', transliteration: 'limani' },
  { word: 'στάση', translation: 'station', transliteration: 'stasi' },
  { word: 'σιδηροδρομικός', translation: 'railway', transliteration: 'siderodromikos' },
  { word: 'λεωφορείο', translation: 'bus', transliteration: 'leoforio' },
  { word: 'ταξί', translation: 'taxi', transliteration: 'taksi' },
  { word: 'ποδήλατο', translation: 'bicycle', transliteration: 'podilato' },
  { word: 'αθλητισμός', translation: 'sports', transliteration: 'athlitismos' },
  { word: 'ποδόσφαιρο', translation: 'soccer', transliteration: 'podosfairo' },
  { word: 'μπάσκετ', translation: 'basketball', transliteration: 'mpasket' },
  { word: 'βόλεϊ', translation: 'volleyball', transliteration: 'bolei' },
  { word: 'τένις', translation: 'tennis', transliteration: 'tenis' },
  { word: 'γκολφ', translation: 'golf', transliteration: 'golf' },
  { word: 'ποδηλασία', translation: 'cycling', transliteration: 'podilasia' },
  { word: 'κωπηλασία', translation: 'rowing', transliteration: 'kopilasia' },
  { word: 'ιππασία', translation: 'horse riding', transliteration: 'ippasia' },
  { word: 'παιχνίδι', translation: 'game', transliteration: 'paichnidi' },
  { word: 'βιβλίο', translation: 'book', transliteration: 'vivlio' },
  { word: 'εφημερίδα', translation: 'newspaper', transliteration: 'efimerida' },
  { word: 'τηλεόραση', translation: 'television', transliteration: 'tileorasi' },
  { word: 'ραδιόφωνο', translation: 'radio', transliteration: 'radiofono' },
  { word: 'κινηματογράφος', translation: 'cinema', transliteration: 'kinimatografos' },
  { word: 'θεάτρο', translation: 'theater', transliteration: 'theatro' },
  { word: 'μουσική', translation: 'music', transliteration: 'mousiki' },
  { word: 'χορός', translation: 'dance', transliteration: 'choros' },
  { word: 'ζωγραφική', translation: 'painting', transliteration: 'zografiki' },
  { word: 'γλυπτική', translation: 'sculpture', transliteration: 'glyptiki' },
  { word: 'αρχιτεκτονική', translation: 'architecture', transliteration: 'architektoniki' },
  { word: 'φωτογραφία', translation: 'photography', transliteration: 'fotografia' },
  { word: 'βίντεο', translation: 'video', transliteration: 'bideo' },
  { word: 'ηλεκτρονικός', translation: 'electronic', transliteration: 'ilektronikos' },
];

const VocabularyBuilder = () => {
  const [currentCardIndex, setCurrentCardIndex] = useState(0);

  const handleNextCard = () => {
    setCurrentCardIndex((prevIndex) => (prevIndex + 1) % popularGreekWords.length);
  };

  const handlePreviousCard = () => {
    setCurrentCardIndex((prevIndex) => (prevIndex - 1 + popularGreekWords.length) % popularGreekWords.length);
  };

  const currentCard = popularGreekWords[currentCardIndex];

  return (
    <div>
      <h2>Popular Words Flashcards</h2>
      <div className="flashcard">
        <h3>{currentCard.word}</h3>
        <p>Translation: {currentCard.translation}</p>
        <p>Transliteration: {currentCard.transliteration}</p>
      </div>
      <button onClick={handlePreviousCard}>Previous</button>
      <button onClick={handleNextCard}>Next</button>
    </div>
  );
};

export default VocabularyBuilder;
